### PR TITLE
Add features

### PR DESCRIPTION
**Pull request by roondar**
In this PR, we add 2 new features:
- Add support to Organizations GalaxyCredentials
- Add  support to users roles

### CODE REVIEW

**Comment by Tioborto** [comment]
Hello @roondar , 
Thank you for your contribution. 
Can you split these features in 2 different PR please ? It will be easier to rollback if a problem is encountered. 
Another remarks, can you add some examples in the directory "example" please ?

**Comment by Tioborto** [comment]
And I don't understand why instance Groups are modified in this PR. Can you give me more information please ?

**Comment by roondar** [comment]
Hello @Tioborto,
Instance groups it's just an other feature like user roles, Organizations GalaxyCredentials, .... 
So why should I only split this feature :interrobang: 
You can create new Instance groups, manage limits and so on.
Don't forget the link with this PR https://github.com/denouche/terraform-provider-awx/pull/21

Ok I'll try to add some examples. :)

**Comment by roondar** [comment]
Btw, it seems @matokovacik worked on it https://github.com/denouche/goawx/pull/14

**Comment by Tioborto** [comment]
Hello @roondar 
I merged Instance groups feature in main branch. Can you rebase your own and resolve conflicts please ? 
Why split this feature ? Because it contains 2 features : 
- Manage Galaxy credentials 
- Manage user roles 

For me these features must create two release. 
Thank you by advance

**Comment by roondar** [comment]
Hello @Tioborto,
I see you are already working on user roles ? https://github.com/denouche/goawx/tree/feat-user-roles

**Pull request closed without merging**
